testcase = [[[  "SOMCHAI CHERPRANG 10",
                "SOMCHAI NATHERINE 5",
                "PRABHAS JENNIS 3",
                "SOMCHAI CHERPRANG 4",
                "DUANGDAO TURTLE 1",
                "EKAPOL TURTLE 1",
                "SETHA TURTLE 1",
                "CHAIRAT TURTLE 1",
                "JENNIS JENNIS 10",
                "PRABHAS JANE 8",
                "MANA CHERPRANG 2",
                "MANEE CHERPRANG 1",
                "CHUJAI TURTLE 1",
                "PITI JENNIS 1",
                "PITI JANE 1",
                "VEERA CHERPRANG 1",
                "1"],
            [   "CHERPRANG, JENNIS, JANE"]],

            [[  "SOMCHAI CHERPRANG 10",
                "SOMCHAI NATHERINE 5",
                "PRABHAS JENNIS 3",
                "SOMCHAI CHERPRANG 4",
                "DUANGDAO TURTLE 1",
                "EKAPOL TURTLE 1",
                "SETHA TURTLE 1",
                "CHAIRAT TURTLE 1",
                "JENNIS JENNIS 10",
                "PRABHAS JANE 8",
                "MANA CHERPRANG 2",
                "MANEE CHERPRANG 1",
                "CHUJAI TURTLE 1",
                "PITI JENNIS 1",
                "PITI JANE 1",
                "VEERA CHERPRANG 1",
                "2"],
            [   "TURTLE, CHERPRANG, JENNIS"]],
            
            [[  "SOMCHAI CHERPRANG 10",
                "SOMCHAI NATHERINE 5",
                "PRABHAS JENNIS 3",
                "SOMCHAI CHERPRANG 4",
                "DUANGDAO TURTLE 1",
                "EKAPOL TURTLE 1",
                "SETHA TURTLE 1",
                "CHAIRAT TURTLE 1",
                "JENNIS JENNIS 10",
                "PRABHAS JANE 8",
                "MANA CHERPRANG 2",
                "MANEE CHERPRANG 1",
                "CHUJAI TURTLE 1",
                "PITI JENNIS 1",
                "PITI JANE 1",
                "VEERA CHERPRANG 1",
                "3"],
            [   "TURTLE, CHERPRANG, JANE"]]]